name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v2

      - name: Exécuter Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible-playbook/deploy.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [webserver]
            20.199.47.109 ansible_python_interpreter=/usr/bin/python3
          options: |
            --user azureuser